name: Deploy to prod

on:
  push:
    branches:
      - main

env:
  SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy-affected:
    runs-on: ubuntu-latest
    name: Deploy changed apps
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: bahmutov/npm-install@v1
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'main' # remember to set this correctly
      - run: "npx nx affected deploy --prod"
